# Generated by Django 3.0.3 on 2020-05-08 01:23

import os
from django.contrib.auth.models import User
from django.db import migrations

def make_admin(apps, schema_editor):
    User.objects.create_superuser(username='admin', password=os.getenv('PGPASSWORD'))


class Migration(migrations.Migration):

    dependencies = [
        ('drf_exercise', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_admin),
    ]
