# Generated by Django 3.0.3 on 2020-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('start_dt', models.DateField()),
                ('start_end', models.DateField()),
            ],
        ),
    ]
